# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db3dfded07210127141bc1976e873dbf2b0fc83cb3faeaa680ee4ade83a76d6bd1fefc9d7be39348d5c6fcbfb03eeecba835a92b33a599ff2df2fceafa9c3717

test:
  secret_key_base: bb43ef7cbde20661d962a42188afc4f791f204a89da3bbe10cab8fa2a1c3c89f6c175562e37c19dc2a904977b388e751d6923c249e3e2082e6f8479d98d8f649

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
